version: '27.3.1'
services:
    book-management:
        image: postgres:16
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: bookLibrary